import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { v5 as uuidv5 } from 'uuid';

const NAMESPACE = 'f4c48c70-99cb-4cbb-85dc-8f66dbaf7657';

const args = new Map(
  process.argv.slice(2).map((arg) => {
    const index = arg.indexOf('=');
    return index === -1
      ? [arg.replace(/^--/, ''), 'true']
      : [arg.slice(2, index), arg.slice(index + 1)];
  })
);

const outputPath = resolve(
  args.get('out') || 'data/migrations/game-engine-d1-rbac-bootstrap.sql'
);
const adminEmail = String(args.get('admin-email') || '').trim().toLowerCase();

function id(scope: string, value: string) {
  return uuidv5(`${scope}:${value}`, NAMESPACE);
}

function q(value: string) {
  return `'${value.replaceAll("'", "''")}'`;
}

const permissionId = id('rbac-permission', '*');
const roleId = id('rbac-role', 'super_admin');
const rolePermissionId = id('rbac-role-permission', 'super_admin:*');

const output = [
  '-- Generated by scripts/export-d1-rbac-bootstrap-sql.ts',
  '-- Minimal RBAC bootstrap for a fresh Game Site Engine D1 database.',
  '-- Safe to re-run.',
  'PRAGMA foreign_keys = ON;',
  'BEGIN TRANSACTION;',
  `INSERT INTO permission (id, code, resource, action, title, description)
VALUES (${q(permissionId)}, '*', 'all', 'all', 'Super Admin', 'All permissions')
ON CONFLICT(code) DO UPDATE SET
  resource=excluded.resource,
  action=excluded.action,
  title=excluded.title,
  description=excluded.description;`,
  `INSERT INTO role (id, name, title, description, status, sort)
VALUES (${q(roleId)}, 'super_admin', 'Super Admin', 'Full system access with all permissions', 'active', 1)
ON CONFLICT(name) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  status=excluded.status,
  sort=excluded.sort;`,
  `INSERT INTO role_permission (id, role_id, permission_id)
SELECT
  ${q(rolePermissionId)},
  r.id,
  p.id
FROM role r
JOIN permission p ON p.code = '*'
WHERE r.name = 'super_admin'
ON CONFLICT(id) DO NOTHING;`,
];

if (adminEmail) {
  output.push(
    `INSERT INTO user_role (id, user_id, role_id)
SELECT
  ${q(id('rbac-user-role', `${adminEmail}:super_admin`))},
  u.id,
  r.id
FROM user u
JOIN role r ON r.name = 'super_admin'
WHERE lower(u.email) = ${q(adminEmail)}
ON CONFLICT(id) DO NOTHING;`
  );
}

output.push('COMMIT;');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${output.join('\n')}\n`, 'utf8');

console.log(`D1 RBAC bootstrap SQL written: ${outputPath}`);
console.log('Role: super_admin');
console.log('Permission: *');
if (adminEmail) {
  console.log(`Admin assignment requested for: ${adminEmail}`);
  console.log(
    'The user must already exist in the target D1 user table before this SQL is applied.'
  );
} else {
  console.log(
    'No --admin-email supplied; this file seeds only the role/permission mapping.'
  );
}
