import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import postgres from 'postgres';
import { v5 as uuidv5 } from 'uuid';

/**
 * Generate a small D1/SQLite SQL file that resets per-site counters after
 * importing legacy DriftBoss data.
 *
 * Why this exists:
 * - legacy `games.view` is global across domains;
 * - V2 counters live on `site_game` and must represent one site's traffic;
 * - copying one global count into every site would create fake analytics.
 *
 * Usage:
 *   LEGACY_DATABASE_URL='postgresql://...' \
 *     pnpm tsx scripts/export-driftboss-v2-reset-stats-sql.ts \
 *       --out=data/migrations/driftboss-v2-reset-stats.sql
 *
 * Optional:
 *   --domain=driftbossgame.org
 */

const NAMESPACE = 'f4c48c70-99cb-4cbb-85dc-8f66dbaf7657';
const legacyUrl = process.env.LEGACY_DATABASE_URL;
if (!legacyUrl) throw new Error('LEGACY_DATABASE_URL is required');

const args = new Map(
  process.argv.slice(2).map((arg) => {
    const index = arg.indexOf('=');
    return index === -1
      ? [arg.replace(/^--/, ''), 'true']
      : [arg.slice(2, index), arg.slice(index + 1)];
  })
);

const outputPath = resolve(
  args.get('out') || 'data/migrations/driftboss-v2-reset-stats.sql'
);
const onlyDomain = normalizeDomain(args.get('domain') || '');

function normalizeDomain(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/^www\./, '')
    .replace(/\/$/, '');
}

function id(scope: string, value: string) {
  return uuidv5(`${scope}:${value}`, NAMESPACE);
}

function q(value: string) {
  return `'${value.replaceAll("'", "''")}'`;
}

const client = postgres(legacyUrl, { prepare: false, max: 1, idle_timeout: 10 });

try {
  const rows = await client.unsafe('SELECT domain FROM game_sites');
  const domains = [...new Set(
    rows
      .map((row: any) => normalizeDomain(row.domain || ''))
      .filter(Boolean)
      .filter((domain) => !onlyDomain || domain === onlyDomain)
  )];

  if (onlyDomain && !domains.includes(onlyDomain)) {
    throw new Error(`Legacy game_sites does not contain domain ${onlyDomain}`);
  }

  const output = [
    '-- Generated by scripts/export-driftboss-v2-reset-stats-sql.ts',
    `-- Generated at ${new Date().toISOString()}`,
    '-- V2 site counters intentionally restart from zero because legacy views were global.',
    'PRAGMA foreign_keys = ON;',
    'BEGIN TRANSACTION;',
    ...domains.map(
      (domain) =>
        `UPDATE site_game SET view_count = 0, like_count = 0, dislike_count = 0, updated_at = ${Date.now()} WHERE site_id = ${q(id('site', domain))};`
    ),
    'COMMIT;',
  ];

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${output.join('\n')}\n`, 'utf8');

  console.log(`Stats reset SQL written: ${outputPath}`);
  console.log(`Sites: ${domains.length}`);
} finally {
  await client.end();
}
