import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { v5 as uuidv5 } from 'uuid';

import {
  GAME_CATEGORY_TAXONOMY,
  LEGACY_GAME_CATEGORY_REMAP,
  type CanonicalGameCategoryKey,
} from '../src/modules/categories/taxonomy';

const NAMESPACE = '89fe5cb5-e85d-4d7c-8b6d-f4bb853335e5';

const args = new Map(
  process.argv.slice(2).map((arg) => {
    const index = arg.indexOf('=');
    return index === -1
      ? [arg.replace(/^--/, ''), 'true']
      : [arg.slice(2, index), arg.slice(index + 1)];
  })
);

const outputPath = resolve(
  args.get('out') || 'data/migrations/canonical-game-taxonomy.sql'
);

function q(value: string) {
  return `'${value.replaceAll("'", "''")}'`;
}

function categoryId(key: string) {
  return uuidv5(`game-category:${key}`, NAMESPACE);
}

function randomIdSql(prefix: string) {
  return `'${prefix}-' || lower(hex(randomblob(16)))`;
}

function targetCategoryIdSql(key: CanonicalGameCategoryKey) {
  return `(SELECT id FROM game_category WHERE key = ${q(key)} LIMIT 1)`;
}

const sourcePriority: Record<string, number> = {
  'racing-games': 100,
  'car-games': 90,
  'sports-games': 100,
  'soccer-games': 90,
  'clicker-games': 100,
  'hypercasual-games': 100,
  'mahjong-games': 100,
  'kids-games': 100,
  'girls-games': 100,
};

const output: string[] = [
  '-- Canonical browser-game taxonomy data migration',
  '-- Generated by scripts/export-category-taxonomy-sql.ts',
  '-- D1 / SQLite only. Safe to re-run.',
  'PRAGMA foreign_keys = ON;',
  'BEGIN TRANSACTION;',
];

for (const definition of GAME_CATEGORY_TAXONOMY) {
  output.push(
    `INSERT INTO game_category (id, key) VALUES (${q(
      categoryId(definition.key)
    )}, ${q(definition.key)}) ON CONFLICT(key) DO NOTHING;`
  );
}

const remaps = Object.entries(LEGACY_GAME_CATEGORY_REMAP)
  .filter(([, target]) => target)
  .sort(
    ([sourceA], [sourceB]) =>
      (sourcePriority[sourceB] || 0) - (sourcePriority[sourceA] || 0)
  ) as Array<[string, CanonicalGameCategoryKey]>;

for (const [sourceKey, targetKey] of remaps) {
  if (sourceKey === targetKey) continue;

  const targetId = targetCategoryIdSql(targetKey);
  const definition = GAME_CATEGORY_TAXONOMY.find(
    (item) => item.key === targetKey
  )!;

  // Preserve global game/category relationships under the canonical category.
  output.push(
    `INSERT OR IGNORE INTO game_category_map (id, game_id, category_id)
SELECT ${randomIdSql('taxonomy-gcm')}, m.game_id, ${targetId}
FROM game_category_map m
JOIN game_category old_category ON old_category.id = m.category_id
WHERE old_category.key = ${q(sourceKey)};`
  );

  // Create the canonical site category where the legacy site category existed.
  output.push(
    `INSERT OR IGNORE INTO site_category
  (id, site_id, category_id, image_url, status, indexable, sort_weight)
SELECT
  ${randomIdSql('taxonomy-sc')},
  source.site_id,
  ${targetId},
  source.image_url,
  source.status,
  source.indexable,
  MAX(source.sort_weight, ${definition.navPriority})
FROM site_category source
JOIN game_category old_category ON old_category.id = source.category_id
WHERE old_category.key = ${q(sourceKey)}
  AND NOT EXISTS (
    SELECT 1
    FROM site_category existing
    WHERE existing.site_id = source.site_id
      AND existing.category_id = ${targetId}
  );`
  );

  output.push(
    `UPDATE site_category
SET sort_weight = MAX(sort_weight, ${definition.navPriority})
WHERE category_id = ${targetId};`
  );

  // Carry over locale SEO/content. Canonical English title/slug win; existing
  // canonical locale rows are never overwritten.
  output.push(
    `INSERT OR IGNORE INTO site_category_locale
  (id, site_id, site_category_id, locale, slug, status, title, meta_title,
   meta_description, description, content)
SELECT
  ${randomIdSql('taxonomy-scl')},
  source.site_id,
  target.id,
  locale.locale,
  ${q(targetKey)},
  locale.status,
  CASE WHEN lower(locale.locale) = 'en' THEN ${q(definition.title)} ELSE locale.title END,
  locale.meta_title,
  locale.meta_description,
  locale.description,
  locale.content
FROM site_category source
JOIN game_category old_category ON old_category.id = source.category_id
JOIN site_category_locale locale ON locale.site_category_id = source.id
JOIN site_category target
  ON target.site_id = source.site_id
 AND target.category_id = ${targetId}
WHERE old_category.key = ${q(sourceKey)};`
  );

  // Carry over each site's game assignments.
  output.push(
    `INSERT OR IGNORE INTO site_game_category
  (id, site_game_id, site_category_id)
SELECT
  ${randomIdSql('taxonomy-sgc')},
  mapping.site_game_id,
  target.id
FROM site_game_category mapping
JOIN site_category source ON source.id = mapping.site_category_id
JOIN game_category old_category ON old_category.id = source.category_id
JOIN site_category target
  ON target.site_id = source.site_id
 AND target.category_id = ${targetId}
WHERE old_category.key = ${q(sourceKey)};`
  );

  // Old top-level pages stay in the DB for rollback/history but disappear from
  // public category queries. Route-level 301 redirects handle safe URL merges.
  output.push(
    `UPDATE site_category
SET status = 'archived', indexable = 0
WHERE category_id = (
  SELECT id FROM game_category WHERE key = ${q(sourceKey)} LIMIT 1
);`
  );
}

// These concepts are useful as tags/themes, not top-level navigation.
for (const [sourceKey, targetKey] of Object.entries(
  LEGACY_GAME_CATEGORY_REMAP
)) {
  if (targetKey !== null) continue;
  output.push(
    `UPDATE site_category
SET status = 'archived', indexable = 0
WHERE category_id = (
  SELECT id FROM game_category WHERE key = ${q(sourceKey)} LIMIT 1
);`
  );
}

// Normalize titles/slugs for canonical English category rows that already
// existed before this migration. SEO body text is deliberately preserved.
for (const definition of GAME_CATEGORY_TAXONOMY) {
  output.push(
    `UPDATE site_category
SET sort_weight = MAX(sort_weight, ${definition.navPriority})
WHERE category_id = ${targetCategoryIdSql(definition.key)};`
  );
  output.push(
    `UPDATE site_category_locale
SET slug = ${q(definition.key)}, title = ${q(definition.title)}
WHERE lower(locale) = 'en'
  AND site_category_id IN (
    SELECT id FROM site_category
    WHERE category_id = ${targetCategoryIdSql(definition.key)}
  );`
  );
}

output.push('COMMIT;');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${output.join('\n\n')}\n`, 'utf8');
console.log(`Canonical taxonomy SQL written: ${outputPath}`);
console.log(`Canonical categories: ${GAME_CATEGORY_TAXONOMY.length}`);
