import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import postgres from 'postgres';
import { v5 as uuidv5 } from 'uuid';

/**
 * Export legacy site-level content that is not part of the main catalog/SEO
 * migration: homepage SEO, legal/contact pages and social links.
 *
 * Usage:
 *   LEGACY_DATABASE_URL='postgresql://...' \
 *     pnpm tsx scripts/export-driftboss-v2-extras-sql.ts \
 *       --out=data/migrations/driftboss-v2-extras.sql
 *
 * Optional:
 *   --domain=driftbossgame.org
 *
 * The output is idempotent and D1/SQLite-compatible.
 */

const NAMESPACE = 'f4c48c70-99cb-4cbb-85dc-8f66dbaf7657';
const legacyUrl = process.env.LEGACY_DATABASE_URL;
if (!legacyUrl) throw new Error('LEGACY_DATABASE_URL is required');

const args = new Map(
  process.argv.slice(2).map((arg) => {
    const index = arg.indexOf('=');
    return index === -1
      ? [arg.replace(/^--/, ''), 'true']
      : [arg.slice(2, index), arg.slice(index + 1)];
  })
);

const outputPath = resolve(
  args.get('out') || 'data/migrations/driftboss-v2-extras.sql'
);
const onlyDomain = normalizeDomain(args.get('domain') || '');

const legacyStaticOrigin = (
  args.get('legacy-static-origin') ||
  process.env.LEGACY_STATIC_ASSET_ORIGIN ||
  'https://static.driftbossgame.org'
).replace(/\/$/, '');

function portableAssetReferences(value: unknown) {
  if (value === null || value === undefined) return value;

  let text = String(value);
  for (const origin of [
    legacyStaticOrigin,
    legacyStaticOrigin.replace(/^https:/i, 'http:'),
  ]) {
    text = text.replaceAll(origin, '');
  }
  return text;
}

function normalizeDomain(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/^www\./, '')
    .replace(/\/$/, '');
}

function id(scope: string, value: string) {
  return uuidv5(`${scope}:${value}`, NAMESPACE);
}

function q(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (value instanceof Date) return String(value.getTime());
  return `'${String(value).replaceAll("'", "''")}'`;
}

function timestamp(value: unknown) {
  if (!value) return Date.now();
  const parsed = new Date(value as any).getTime();
  return Number.isFinite(parsed) ? parsed : Date.now();
}

function sqlInsert(
  table: string,
  columns: string[],
  values: unknown[],
  conflict: string,
  updateColumns: string[]
) {
  const update = updateColumns
    .map((column) => `${column}=excluded.${column}`)
    .join(', ');
  return `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values
    .map(q)
    .join(', ')}) ON CONFLICT ${conflict} DO UPDATE SET ${update};`;
}

const client = postgres(legacyUrl, { prepare: false, max: 1, idle_timeout: 10 });

async function rows(table: string) {
  try {
    return await client.unsafe(`SELECT * FROM ${table}`);
  } catch (error) {
    console.warn(
      `Skipping unavailable legacy table ${table}:`,
      (error as Error).message
    );
    return [] as any[];
  }
}

const pageDefs = [
  { field: 'about_us', slug: 'about-us', title: 'About Us' },
  { field: 'contact_us', slug: 'contact-us', title: 'Contact Us' },
  { field: 'privacy_policy', slug: 'privacy-policy', title: 'Privacy Policy' },
  { field: 'terms_of_service', slug: 'terms-of-service', title: 'Terms of Service' },
] as const;

try {
  const [legacySites, legacySocialLinks] = await Promise.all([
    rows('game_sites'),
    rows('social_links'),
  ]);

  const output: string[] = [
    '-- Generated by scripts/export-driftboss-v2-extras-sql.ts',
    `-- Generated at ${new Date().toISOString()}`,
    '-- Apply after the main driftboss-v2.sql migration.',
    'PRAGMA foreign_keys = ON;',
    'BEGIN TRANSACTION;',
  ];

  let siteCount = 0;
  let pageCount = 0;
  let socialSiteCount = 0;

  for (const row of legacySites) {
    const domain = normalizeDomain(row.domain || '');
    if (!domain || (onlyDomain && domain !== onlyDomain)) continue;
    siteCount += 1;
    const siteId = id('site', domain);
    const createdAt = timestamp(row.created_at);
    const updatedAt = timestamp(row.updated_at || row.created_at);

    output.push(
      sqlInsert(
        'site_locale',
        [
          'id',
          'site_id',
          'locale',
          'status',
          'title',
          'meta_title',
          'meta_description',
          'intro',
          'content',
          'created_at',
          'updated_at',
        ],
        [
          id('site-locale', `${domain}:en`),
          siteId,
          'en',
          'published',
          row.site_name || domain,
          row.meta_title || null,
          row.meta_desc || null,
          null,
          portableAssetReferences(row.seo_content) || null,
          createdAt,
          updatedAt,
        ],
        '(site_id, locale)',
        [
          'status',
          'title',
          'meta_title',
          'meta_description',
          'content',
          'updated_at',
        ]
      )
    );

    for (const page of pageDefs) {
      const content = row[page.field];
      if (!content || !String(content).trim()) continue;
      pageCount += 1;
      const postId = id('site-post', `${domain}:page:${page.slug}`);

      output.push(
        sqlInsert(
          'site_post',
          [
            'id',
            'site_id',
            'type',
            'status',
            'indexable',
            'featured',
            'published_at',
            'created_at',
            'updated_at',
          ],
          [
            postId,
            siteId,
            'page',
            'published',
            1,
            0,
            createdAt,
            createdAt,
            updatedAt,
          ],
          '(id)',
          ['status', 'indexable', 'published_at', 'updated_at']
        )
      );

      output.push(
        sqlInsert(
          'site_post_locale',
          [
            'id',
            'site_id',
            'site_post_id',
            'locale',
            'slug',
            'status',
            'title',
            'meta_title',
            'meta_description',
            'description',
            'image_url',
            'content',
            'created_at',
            'updated_at',
          ],
          [
            id('site-post-locale', `${domain}:page:${page.slug}:en`),
            siteId,
            postId,
            'en',
            page.slug,
            'published',
            page.title,
            `${page.title} | ${row.site_name || domain}`,
            null,
            null,
            null,
            portableAssetReferences(content),
            createdAt,
            updatedAt,
          ],
          '(site_post_id, locale)',
          [
            'site_id',
            'slug',
            'status',
            'title',
            'meta_title',
            'content',
            'updated_at',
          ]
        )
      );
    }
  }

  const socialByDomain = new Map<string, Array<{ name: string; url: string }>>();
  for (const row of legacySocialLinks) {
    const domain = normalizeDomain(row.domain || '');
    if (!domain || (onlyDomain && domain !== onlyDomain)) continue;
    const items = socialByDomain.get(domain) || [];
    items.push({
      name: String(row.display_name || '').trim(),
      url: String(row.url || '').trim(),
    });
    socialByDomain.set(domain, items);
  }

  for (const [domain, items] of socialByDomain) {
    if (!items.length) continue;
    socialSiteCount += 1;
    const siteId = id('site', domain);
    output.push(
      sqlInsert(
        'site_setting',
        ['id', 'site_id', 'key', 'value', 'created_at', 'updated_at'],
        [
          id('site-setting', `${domain}:social_links`),
          siteId,
          'social_links',
          JSON.stringify(items),
          Date.now(),
          Date.now(),
        ],
        '(site_id, key)',
        ['value', 'updated_at']
      )
    );
  }

  output.push('COMMIT;');
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${output.join('\n')}\n`, 'utf8');

  console.log(`Migration extras SQL written: ${outputPath}`);
  console.log(`Homepage site locales: ${siteCount}`);
  console.log(`Static pages: ${pageCount}`);
  console.log(`Sites with social links: ${socialSiteCount}`);
} finally {
  await client.end();
}
