import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { hashPassword } from 'better-auth/crypto';
import { v5 as uuidv5 } from 'uuid';

const NAMESPACE = 'da833b12-2e3b-44ea-9be2-c43f017c7c33';

const args = new Map(
  process.argv.slice(2).map((arg) => {
    const index = arg.indexOf('=');
    return index === -1
      ? [arg.replace(/^--/, ''), 'true']
      : [arg.slice(2, index), arg.slice(index + 1)];
  })
);

const email = String(
  args.get('email') || process.env.GAME_ADMIN_EMAIL || ''
)
  .trim()
  .toLowerCase();
const password = String(
  args.get('password') || process.env.GAME_ADMIN_PASSWORD || ''
);
const name = String(args.get('name') || 'Admin').trim() || 'Admin';
const outputPath = resolve(
  args.get('out') || 'data/migrations/d1-preview-admin-bootstrap.sql'
);

if (!email || !email.includes('@')) {
  throw new Error(
    'Admin email is required via GAME_ADMIN_EMAIL or --email=...'
  );
}
if (password.length < 12) {
  throw new Error(
    'Admin password must be at least 12 characters via GAME_ADMIN_PASSWORD or --password=...'
  );
}

function id(scope: string, value: string) {
  return uuidv5(`${scope}:${value}`, NAMESPACE);
}

function q(value: unknown) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
}

const now = Date.now();
const passwordHash = await hashPassword(password);

const userId = id('user', email);
const accountId = id('credential-account', email);
const roleId = id('role', 'super_admin');
const permissionId = id('permission', '*');
const rolePermissionId = id('role-permission', 'super_admin:*');
const userRoleId = id('user-role', `${email}:super_admin`);

const statements = [
  '-- Generated by scripts/export-d1-admin-bootstrap-sql.ts',
  '-- Contains a password hash. Keep this file local/gitignored and delete it after use.',
  'PRAGMA foreign_keys = ON;',
  'BEGIN TRANSACTION;',
  `INSERT INTO permission (id, code, resource, action, title, description, created_at, updated_at)
VALUES (${q(permissionId)}, '*', 'all', 'all', 'Super Admin', 'All permissions', ${now}, ${now})
ON CONFLICT(code) DO UPDATE SET resource=excluded.resource, action=excluded.action, title=excluded.title, description=excluded.description, updated_at=excluded.updated_at;`,
  `INSERT INTO role (id, name, title, description, status, sort, created_at, updated_at)
VALUES (${q(roleId)}, 'super_admin', 'Super Admin', 'Full system access', 'active', 1, ${now}, ${now})
ON CONFLICT(name) DO UPDATE SET title=excluded.title, description=excluded.description, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;`,
  `INSERT INTO role_permission (id, role_id, permission_id, created_at, updated_at)
SELECT ${q(rolePermissionId)}, r.id, p.id, ${now}, ${now}
FROM role r, permission p
WHERE r.name = 'super_admin' AND p.code = '*'
ON CONFLICT(id) DO UPDATE SET role_id=excluded.role_id, permission_id=excluded.permission_id, updated_at=excluded.updated_at;`,
  `INSERT INTO user (id, name, email, email_verified, image, created_at, updated_at, utm_source, ip, locale)
VALUES (${q(userId)}, ${q(name)}, ${q(email)}, 1, NULL, ${now}, ${now}, '', '', '')
ON CONFLICT(email) DO UPDATE SET name=excluded.name, email_verified=1, updated_at=excluded.updated_at;`,
  `INSERT INTO account (id, account_id, provider_id, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at)
SELECT ${q(accountId)}, u.id, 'credential', u.id, NULL, NULL, NULL, NULL, NULL, NULL, ${q(passwordHash)}, ${now}, ${now}
FROM user u
WHERE u.email = ${q(email)}
ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id, user_id=excluded.user_id, password=excluded.password, updated_at=excluded.updated_at;`,
  `INSERT INTO user_role (id, user_id, role_id, created_at, updated_at, expires_at)
SELECT ${q(userRoleId)}, u.id, r.id, ${now}, ${now}, NULL
FROM user u, role r
WHERE u.email = ${q(email)} AND r.name = 'super_admin'
ON CONFLICT(id) DO UPDATE SET user_id=excluded.user_id, role_id=excluded.role_id, expires_at=NULL, updated_at=excluded.updated_at;`,
  'COMMIT;',
];

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${statements.join('\n')}\n`, 'utf8');

console.log(`D1 admin bootstrap SQL written: ${outputPath}`);
console.log(`Admin email: ${email}`);
console.log('Password/hash not printed. Delete the generated SQL after applying it.');
