import { writeFile } from 'node:fs/promises';
import postgres from 'postgres';
import { v5 as uuidv5 } from 'uuid';

const NAMESPACE = '40be9f45-0c7a-5d1a-b4aa-7d624b7f5393';
const now = Date.now();

function arg(name: string) {
  const prefix = `--${name}=`;
  const item = process.argv.find((value) => value.startsWith(prefix));
  return item?.slice(prefix.length);
}

function normalizeDomain(value: string) {
  return value.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/$/, '');
}

function siteKey(domain: string) {
  return normalizeDomain(domain).replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function slug(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function id(kind: string, key: string) {
  return uuidv5(`${kind}:${key}`, NAMESPACE);
}

function text(value: unknown): string {
  if (value == null) return 'NULL';
  return `'${String(value).replaceAll("'", "''")}'`;
}

function number(value: unknown, fallback = 0) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? String(parsed) : String(fallback);
}

function bool(value: unknown) {
  return value ? '1' : '0';
}

function json(value: unknown) {
  return text(JSON.stringify(value));
}

function epoch(value: unknown) {
  if (!value) return String(now);
  const date = new Date(String(value));
  return Number.isNaN(date.getTime()) ? String(now) : String(date.getTime());
}

function localeOf(row: Record<string, any>) {
  return String(row.locale || 'en').trim() || 'en';
}

function optional(row: Record<string, any>, ...keys: string[]) {
  for (const key of keys) {
    if (row[key] != null) return row[key];
  }
  return null;
}

async function safeQuery<T extends Record<string, any>>(
  sql: postgres.Sql,
  query: string
): Promise<T[]> {
  try {
    return (await sql.unsafe(query)) as T[];
  } catch (error: any) {
    if (String(error?.code) === '42P01') return [];
    throw error;
  }
}

const sourceUrl = process.env.LEGACY_DATABASE_URL;
if (!sourceUrl) {
  console.error('LEGACY_DATABASE_URL is required. It must point to the legacy driftbossgame PostgreSQL/Supabase database.');
  process.exit(1);
}

const onlyDomain = arg('domain');
const output = arg('out') || 'data/driftbossgame-v2-migration.sql';
const sql = postgres(sourceUrl, { prepare: false, max: 1, idle_timeout: 10 });

try {
  const [games, sites, seoGames, categories, seoCategories, gameCategories, blogs, socialLinks] =
    await Promise.all([
      safeQuery(sql, 'select * from games order by id'),
      safeQuery(sql, 'select * from game_sites order by id'),
      safeQuery(sql, 'select * from seo_games order by id'),
      safeQuery(sql, 'select * from categories order by id'),
      safeQuery(sql, 'select * from seo_categories order by id'),
      safeQuery(sql, 'select * from game_categories order by id'),
      safeQuery(sql, 'select * from blogs order by id'),
      safeQuery(sql, 'select * from social_links order by id'),
    ]);

  const siteRows = sites.filter((row) => !onlyDomain || normalizeDomain(row.domain) === normalizeDomain(onlyDomain));
  const domains = new Set(siteRows.map((row) => normalizeDomain(row.domain)));

  const seoGameRows = seoGames.filter((row) => domains.has(normalizeDomain(row.domain)));
  const seoCategoryRows = seoCategories.filter((row) => domains.has(normalizeDomain(row.domain)));
  const blogRows = blogs.filter((row) => row.domain && domains.has(normalizeDomain(row.domain)));
  const socialRows = socialLinks.filter((row) => domains.has(normalizeDomain(row.domain)));

  const gameByKey = new Map(games.map((row) => [String(row.game_key), row]));
  const categoryByKey = new Map(categories.map((row) => [String(row.category), row]));

  const statements: string[] = [
    '-- Generated by scripts/migrate-driftbossgame-to-d1.ts',
    '-- Review this file before applying it to production D1.',
    'PRAGMA foreign_keys = ON;',
    'BEGIN TRANSACTION;',
  ];

  for (const row of games) {
    const gameKey = String(row.game_key);
    const gameId = id('game', gameKey);
    statements.push(`INSERT INTO game_catalog (
  id, key, title, description, embed_url, source_url, image_url, provider, embed_type,
  orientation, aspect_ratio, status, created_at, updated_at
) VALUES (
  ${text(gameId)}, ${text(gameKey)}, ${text(row.title)}, ${text(row.description)}, ${text(row.url)}, NULL,
  ${text(row.image)}, 'legacy-driftbossgame', 'iframe', NULL, NULL, 'active', ${epoch(row.created_at)}, ${now}
) ON CONFLICT(key) DO UPDATE SET
  title=excluded.title, description=excluded.description, embed_url=excluded.embed_url,
  image_url=excluded.image_url, updated_at=excluded.updated_at;`);
  }

  for (const row of categories) {
    const key = String(row.category);
    statements.push(`INSERT INTO game_category (id, key, created_at, updated_at)
VALUES (${text(id('category', key))}, ${text(key)}, ${epoch(row.created_at)}, ${now})
ON CONFLICT(key) DO UPDATE SET updated_at=excluded.updated_at;`);
  }

  for (const row of gameCategories) {
    if (!gameByKey.has(String(row.game_key)) || !categoryByKey.has(String(row.category))) continue;
    const gameId = id('game', String(row.game_key));
    const categoryId = id('category', String(row.category));
    statements.push(`INSERT INTO game_category_map (id, game_id, category_id, created_at)
VALUES (${text(id('game-category', `${row.game_key}:${row.category}`))}, ${text(gameId)}, ${text(categoryId)}, ${epoch(row.created_at)})
ON CONFLICT(game_id, category_id) DO NOTHING;`);
  }

  for (const row of siteRows) {
    const domain = normalizeDomain(row.domain);
    const sid = id('site', domain);
    const locales = new Set(
      seoGameRows
        .filter((item) => normalizeDomain(item.domain) === domain)
        .map(localeOf)
    );
    locales.add('en');

    statements.push(`INSERT INTO game_site (
  id, key, domain, name, status, default_locale, enabled_locales, logo_url, favicon_url, created_at, updated_at
) VALUES (
  ${text(sid)}, ${text(siteKey(domain))}, ${text(domain)}, ${text(row.site_name || domain)}, 'active', 'en',
  ${json([...locales])}, ${text(row.logo_url)}, ${text(row.favicon_url)}, ${epoch(row.created_at)}, ${epoch(row.updated_at)}
) ON CONFLICT(key) DO UPDATE SET
  domain=excluded.domain, name=excluded.name, enabled_locales=excluded.enabled_locales,
  logo_url=excluded.logo_url, favicon_url=excluded.favicon_url, updated_at=excluded.updated_at;`);

    statements.push(`INSERT INTO site_locale (
  id, site_id, locale, status, title, meta_title, meta_description, intro, content, created_at, updated_at
) VALUES (
  ${text(id('site-locale', `${domain}:en`))}, ${text(sid)}, 'en', 'published', ${text(row.site_name || domain)},
  ${text(row.meta_title)}, ${text(row.meta_desc)}, NULL, ${text(row.seo_content)}, ${epoch(row.created_at)}, ${epoch(row.updated_at)}
) ON CONFLICT(site_id, locale) DO UPDATE SET
  title=excluded.title, meta_title=excluded.meta_title, meta_description=excluded.meta_description,
  content=excluded.content, status='published', updated_at=excluded.updated_at;`);

    const legalPages = [
      ['about-us', 'About Us', row.about_us],
      ['contact-us', 'Contact Us', row.contact_us],
      ['privacy-policy', 'Privacy Policy', row.privacy_policy],
      ['terms-of-service', 'Terms of Service', row.terms_of_service],
    ];
    for (const [pageSlug, pageTitle, pageContent] of legalPages) {
      if (!pageContent) continue;
      const postId = id('site-post', `${domain}:page:${pageSlug}`);
      statements.push(`INSERT INTO site_post (
  id, site_id, type, status, indexable, featured, author_name, author_image, published_at, created_at, updated_at
) VALUES (${text(postId)}, ${text(sid)}, 'page', 'published', 1, 0, NULL, NULL, ${now}, ${now}, ${now})
ON CONFLICT(id) DO UPDATE SET status='published', indexable=1, updated_at=excluded.updated_at;`);
      statements.push(`INSERT INTO site_post_locale (
  id, site_id, site_post_id, locale, slug, status, title, meta_title, meta_description, description, image_url, content, created_at, updated_at
) VALUES (
  ${text(id('site-post-locale', `${domain}:page:${pageSlug}:en`))}, ${text(sid)}, ${text(postId)}, 'en', ${text(pageSlug)}, 'published',
  ${text(pageTitle)}, ${text(`${pageTitle} | ${row.site_name || domain}`)}, NULL, NULL, NULL, ${text(pageContent)}, ${now}, ${now}
) ON CONFLICT(site_post_id, locale) DO UPDATE SET
  slug=excluded.slug, status='published', title=excluded.title, content=excluded.content, updated_at=excluded.updated_at;`);
    }
  }

  for (const row of seoGameRows) {
    const domain = normalizeDomain(row.domain);
    const gameKey = String(row.game_key);
    const gameRow = gameByKey.get(gameKey);
    if (!gameRow) continue;
    const sid = id('site', domain);
    const gid = id('game', gameKey);
    const siteGameId = id('site-game', `${domain}:${gameKey}`);
    const locale = localeOf(row);
    const localeSlug = optional(row, 'slug') || gameKey;

    statements.push(`INSERT INTO site_game (
  id, site_id, game_id, status, indexable, featured, hot, sort_weight, view_count, like_count, dislike_count,
  published_at, created_at, updated_at
) VALUES (
  ${text(siteGameId)}, ${text(sid)}, ${text(gid)}, 'published', 1, 0, 0, 0, 0, 0, 0,
  ${epoch(row.created_at)}, ${epoch(row.created_at)}, ${now}
) ON CONFLICT(site_id, game_id) DO UPDATE SET status='published', indexable=1, updated_at=excluded.updated_at;`);

    statements.push(`INSERT INTO site_game_locale (
  id, site_id, site_game_id, locale, slug, status, title, meta_title, meta_description, intro, description,
  content, how_to_play, controls, features, faq, created_at, updated_at
) VALUES (
  ${text(id('site-game-locale', `${domain}:${gameKey}:${locale}`))}, ${text(sid)}, ${text(siteGameId)}, ${text(locale)},
  ${text(slug(String(localeSlug)))}, 'published', ${text(optional(row, 'title') || gameRow.title)},
  ${text(optional(row, 'meta_title'))}, ${text(optional(row, 'meta_desc', 'meta_description'))}, NULL,
  ${text(gameRow.description)}, ${text(optional(row, 'seo_content'))}, NULL, NULL, NULL, NULL,
  ${epoch(row.created_at)}, ${now}
) ON CONFLICT(site_game_id, locale) DO UPDATE SET
  slug=excluded.slug, status='published', title=excluded.title, meta_title=excluded.meta_title,
  meta_description=excluded.meta_description, description=excluded.description, content=excluded.content,
  updated_at=excluded.updated_at;`);
  }

  for (const row of seoCategoryRows) {
    const domain = normalizeDomain(row.domain);
    const categoryKey = String(row.category);
    if (!categoryByKey.has(categoryKey)) continue;
    const sid = id('site', domain);
    const categoryId = id('category', categoryKey);
    const siteCategoryId = id('site-category', `${domain}:${categoryKey}`);
    const locale = localeOf(row);

    statements.push(`INSERT INTO site_category (
  id, site_id, category_id, status, indexable, sort_weight, created_at, updated_at
) VALUES (${text(siteCategoryId)}, ${text(sid)}, ${text(categoryId)}, 'published', 1, 0, ${epoch(row.created_at)}, ${now})
ON CONFLICT(site_id, category_id) DO UPDATE SET status='published', indexable=1, updated_at=excluded.updated_at;`);

    statements.push(`INSERT INTO site_category_locale (
  id, site_id, site_category_id, locale, slug, status, title, meta_title, meta_description, description, content, created_at, updated_at
) VALUES (
  ${text(id('site-category-locale', `${domain}:${categoryKey}:${locale}`))}, ${text(sid)}, ${text(siteCategoryId)}, ${text(locale)},
  ${text(slug(categoryKey))}, 'published', ${text(optional(row, 'title') || categoryKey)}, ${text(optional(row, 'meta_title'))},
  ${text(optional(row, 'meta_desc', 'meta_description'))}, ${text(categoryByKey.get(categoryKey)?.description)},
  ${text(optional(row, 'seo_content'))}, ${epoch(row.created_at)}, ${now}
) ON CONFLICT(site_category_id, locale) DO UPDATE SET
  slug=excluded.slug, status='published', title=excluded.title, meta_title=excluded.meta_title,
  meta_description=excluded.meta_description, description=excluded.description, content=excluded.content,
  updated_at=excluded.updated_at;`);
  }

  for (const row of blogRows) {
    const domain = normalizeDomain(row.domain);
    const sid = id('site', domain);
    const postId = id('site-post', `${domain}:article:${row.slug}`);
    const locale = localeOf(row);
    const status = row.published === false ? 'draft' : 'published';
    const publishedAt = row.published === false ? 'NULL' : epoch(row.created_at);

    statements.push(`INSERT INTO site_post (
  id, site_id, type, status, indexable, featured, author_name, author_image, published_at, created_at, updated_at
) VALUES (
  ${text(postId)}, ${text(sid)}, 'article', ${text(status)}, ${bool(row.published !== false)}, 0, NULL, NULL,
  ${publishedAt}, ${epoch(row.created_at)}, ${epoch(row.updated_at)}
) ON CONFLICT(id) DO UPDATE SET status=excluded.status, indexable=excluded.indexable, updated_at=excluded.updated_at;`);

    statements.push(`INSERT INTO site_post_locale (
  id, site_id, site_post_id, locale, slug, status, title, meta_title, meta_description, description, image_url, content, created_at, updated_at
) VALUES (
  ${text(id('site-post-locale', `${domain}:article:${row.slug}:${locale}`))}, ${text(sid)}, ${text(postId)}, ${text(locale)},
  ${text(slug(String(row.slug)))}, ${text(status)}, ${text(row.title)}, ${text(row.meta_title)}, ${text(row.meta_description)},
  ${text(row.summary)}, ${text(row.cover_image)}, ${text(row.content)}, ${epoch(row.created_at)}, ${epoch(row.updated_at)}
) ON CONFLICT(site_post_id, locale) DO UPDATE SET
  slug=excluded.slug, status=excluded.status, title=excluded.title, meta_title=excluded.meta_title,
  meta_description=excluded.meta_description, description=excluded.description, image_url=excluded.image_url,
  content=excluded.content, updated_at=excluded.updated_at;`);
  }

  for (const siteRow of siteRows) {
    const domain = normalizeDomain(siteRow.domain);
    const links = socialRows
      .filter((row) => normalizeDomain(row.domain) === domain)
      .map((row) => ({ displayName: row.display_name, url: row.url }));
    if (!links.length) continue;
    const sid = id('site', domain);
    statements.push(`INSERT INTO site_setting (id, site_id, key, value, created_at, updated_at)
VALUES (${text(id('site-setting', `${domain}:social_links`))}, ${text(sid)}, 'social_links', ${json(links)}, ${now}, ${now})
ON CONFLICT(site_id, key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;`);
  }

  // Preserve category membership only when the game and category are both explicitly
  // present on the same site. This prevents a global taxonomy row from exposing content
  // that the legacy site never had site-specific SEO for.
  for (const domain of domains) {
    const siteSeoGames = new Set(
      seoGameRows
        .filter((row) => normalizeDomain(row.domain) === domain)
        .map((row) => String(row.game_key))
    );
    const siteSeoCategories = new Set(
      seoCategoryRows
        .filter((row) => normalizeDomain(row.domain) === domain)
        .map((row) => String(row.category))
    );
    for (const row of gameCategories) {
      const gameKey = String(row.game_key);
      const categoryKey = String(row.category);
      if (!siteSeoGames.has(gameKey) || !siteSeoCategories.has(categoryKey)) continue;
      statements.push(`INSERT INTO site_game_category (id, site_game_id, site_category_id, created_at)
VALUES (
  ${text(id('site-game-category', `${domain}:${gameKey}:${categoryKey}`))},
  ${text(id('site-game', `${domain}:${gameKey}`))},
  ${text(id('site-category', `${domain}:${categoryKey}`))},
  ${now}
) ON CONFLICT(site_game_id, site_category_id) DO NOTHING;`);
    }
  }

  statements.push('COMMIT;');

  await writeFile(output, `${statements.join('\n\n')}\n`, 'utf8');

  console.log('Legacy migration SQL generated.');
  console.log(`Output: ${output}`);
  console.log(`Sites: ${siteRows.length}`);
  console.log(`Global games: ${games.length}`);
  console.log(`Site-game SEO rows: ${seoGameRows.length}`);
  console.log(`Global categories: ${categories.length}`);
  console.log(`Site-category SEO rows: ${seoCategoryRows.length}`);
  console.log(`Blogs: ${blogRows.length}`);
  console.log('Legacy global view/like/dislike counts were intentionally not copied into per-site counters.');
  console.log('Review the SQL, then apply with: wrangler d1 execute <DB_NAME> --remote --file=<output>');
} finally {
  await sql.end();
}
